import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { hookCommand, readJsonObject, writeJson } from "../hook-config.js";
import { copyBundledSkills } from "../skills.js";
import type { PlatformInstallContext, PlatformInstallResult, PlatformInstaller, WorkingMemoryUpdateInput } from "./types.js";

const generatedMarker = "Generated by Greplica";

// Cursor lifecycle hooks Greplica listens on. beforeSubmitPrompt maps to the
// canonical UserPromptSubmit event and stop maps to Stop (see hook-input.ts).
const cursorHookEvents = ["beforeSubmitPrompt", "stop"] as const;

// Cursor reads user-scoped skills and hooks from ~/.cursor (overridable via
// CURSOR_HOME for tests) and project rules from <repo>/.cursor/rules. Per-prompt
// guidance rides an always-applied rule rather than a hook, because Cursor's
// beforeSubmitPrompt hook cannot inject context into the prompt.
function cursorHome(): string {
  return process.env.CURSOR_HOME ?? join(homedir(), ".cursor");
}

export const cursorInstaller: PlatformInstaller = {
  platform: "cursor",
  install(context: PlatformInstallContext): PlatformInstallResult {
    const skills = copyBundledSkills(join(cursorHome(), "skills"));
    const rulePath = writeCursorRule(context.repoRoot);
    const result: PlatformInstallResult = {
      skills,
      supportsAutoMemoryUpdates: false,
      rules: {
        platform: "cursor",
        configFiles: [rulePath],
      },
    };

    if (context.hooks) {
      const command = hookCommand("cursor");
      const hooksPath = writeCursorHooks(command);
      result.hooks = {
        platform: "cursor",
        configFiles: [hooksPath],
        events: [...cursorHookEvents],
        command,
      };
    }

    return result;
  },
  sessionSourceRef(sessionId: string): string {
    return `cursor-session:${sessionId}`;
  },
  sessionIdFromSourceRef(ref: string): string | undefined {
    return ref.startsWith("cursor-session:") ? ref.slice("cursor-session:".length) : undefined;
  },
  transcriptToMarkdown(_transcript: string): string {
    // Cursor transcript projection lands in a follow-up change; returning an
    // empty projection makes the background worker skip cleanly until then.
    return "";
  },
  async runWorkingMemoryUpdate(_input: WorkingMemoryUpdateInput): Promise<void> {
    throw new Error("Cursor background working-memory updates are not supported yet.");
  },
};

function writeCursorRule(repoRoot: string): string {
  const rulesDir = join(repoRoot, ".cursor", "rules");
  mkdirSync(rulesDir, { recursive: true });
  const rulePath = cursorRulePath(rulesDir);
  writeFileSync(rulePath, cursorRuleContent(), "utf8");
  return rulePath;
}

// Never overwrite a user-authored greplica.mdc: reuse the file only when it was
// generated by Greplica; otherwise fall back to greplica-1.mdc, greplica-2.mdc, ...
function cursorRulePath(rulesDir: string): string {
  const candidates = [join(rulesDir, "greplica.mdc")];
  for (let index = 1; index < 100; index += 1) candidates.push(join(rulesDir, `greplica-${index}.mdc`));

  const generated = candidates.find((candidate) => existsSync(candidate) && readFileSync(candidate, "utf8").includes(generatedMarker));
  if (generated !== undefined) return generated;

  const available = candidates.find((candidate) => !existsSync(candidate));
  if (available !== undefined) return available;

  throw new Error(`Could not find a safe Cursor rule path in ${rulesDir}.`);
}

// Merge our hook command into ~/.cursor/hooks.json without disturbing other
// hooks the user (or another tool) has registered. Re-running is idempotent.
function writeCursorHooks(command: string): string {
  const hooksPath = join(cursorHome(), "hooks.json");
  const base = readJsonObject(hooksPath);
  const version = typeof base.version === "number" ? base.version : 1;
  const hooks = isRecord(base.hooks) ? { ...base.hooks } : {};

  for (const event of cursorHookEvents) {
    const existing = Array.isArray(hooks[event]) ? hooks[event] : [];
    const kept = existing.filter((handler) => !(isRecord(handler) && handler.command === command));
    hooks[event] = [...kept, { command }];
  }

  writeJson(hooksPath, { ...base, version, hooks });
  return hooksPath;
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function cursorRuleContent(): string {
  return `---
description: Use Greplica repo memory when working in this project
globs:
  - "**/*"
alwaysApply: true
---
<!-- ${generatedMarker}. Safe to delete; recreated on greplica install. -->

Greplica stores long-term, searchable engineering memory for this repository.

Before broad manual exploration, run:

\`\`\`bash
greplica graph context "<focused question>"
\`\`\`

Use the returned components, flows, claims, and code anchors to decide where to look first.

For a repository that has no memory yet, use the \`greplica-bootstrap\` skill.

Near the end of a useful work session, use the \`greplica-update-working-memory\` skill so durable decisions, constraints, changed workflows, and follow-up tasks are saved.

Do not store secrets, transient debugging chatter, or raw command logs as Greplica memory.
`;
}
